### ISSUE TITLE
[Security Issue] Move fork launchatlogin from main repo

### ISSUE THREAD

**Issue by mstarke** [georgesnow/MacPass#10]
GitHub had a security bug that allowed branches to be created on the wrong repository. This resulted in your "launchatlogin" branch being created on the main MacPass repository instead of on your fork.

I would like to delete the branch and move it to your fork.

If you have any questions we could clear it in this issue or via email.

**Comment by georgesnow** [comment]
oh yeah, thats totally fine.

**Comment by georgesnow** [comment]
you can send me an email letting me know if there is anything I need to do to prevent the issue in the future etc..

**Comment by mstarke** [comment]
Crap. I might have deleted the fork on my end under the assumption you got a local version and can simply push it back upstream. Seems I was wrong and royally fucked up your work…

**Comment by georgesnow** [comment]
No worries. Figure out something. I saw I can clone pull request. I might try that and nuke the .git folder locally. Then push it back to my fork on a new branch

**Comment by georgesnow** [comment]
@mstarke it looks like my branch still exists on the main repo. So maybe I can salvage it that way?

**Comment by mstarke** [comment]
Awesome. I thought I did go on with the deletion but might have missed it. Thank goodness for this "mistake" on my part. I'm going to delete it on the main repo now.
